version: '3' 

services:  
  refresh-gpt-chat:
    ports:
      - "127.0.0.1:8900:8082"
    # 该服务使用的 Docker 镜像
    image: yangclivia/refresh-gpt-chat:latest  
    # Java 的环境变量 （可适当调节，用copilot可以适当调大点，具体可问gpt了解）
    environment:  
      - JAVA_OPTS=-XX:+UseParallelGC -Xms64m -Xmx64m -XX:MaxMetaspaceSize=64m  
    # 为该服务创建的容器的名称
    container_name: refresh-gpt-chat
    # 容器总是重新启动
    restart: always  
    # 容器运行的用户
    user: root  
    # 容器的网络模式
    network_mode: host
    command:  
      - --log=info
      # 自定义端口号
      - --server.port=8082
      # 自定义前缀
      - --server.servlet.context-path=/tokensTool
      # 选择刷新access_token的服务商ninja/xyhelper/oai
      - --getAccessTokenService=xyhelper
      # ninja get accessToken Url，如果getAccessTokenService填了ninja，该项必填
      - --getAccessTokenUrl_ninja=http(s)://ip+port/url/auth/refresh_token
      # is cancel gpt-4-gizmo
      - --isCancelGizmo=true
      # max_threads
      - --max_threads=300